database:
  name: captive_portal.db
  
site:
  name: Welcome to ShadoWall
  url: http://www.yoursite.com

support:
  email: nomail@nodomain.com
  url: http://yourhelpdesk.com
  phone: +52 55 1010101010101

dhcp:
  file: /Users/alex/Projects/Ruby/shadowall/tmp/dhcpd.leases
  backward: 7